project_id = "laucbnbffvygnrmogavs"

[functions.ai-goal-plan]
verify_jwt = true

[functions.generate-goal-plan]
verify_jwt = true

[functions.categorize-app]
verify_jwt = false

[functions.recategorize-existing-apps]
verify_jwt = false
